stages:
  - build_image
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: qevent_intership_stream_data_processor_image

build_docker_image:
  stage: build_image
  only:
    changes:
      - Dockerfile
      - .gitlab-ci.yml
  image: docker:stable
  script:
    - docker info
    - docker build --build-arg GCC_IMAGE_VERSION=10.2.0 -t $DOCKER_IMAGE_NAME .

stream_data_processor_build:
  stage: build
  image: $DOCKER_IMAGE_NAME
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make test_main
  artifacts:
    paths:
      - build

stream_data_processor_test:
  stage: test
  image: $DOCKER_IMAGE_NAME
  script:
    - cd build
    - ./test/test_main
  dependencies:
    - stream_data_processor_build

