stages:
  - build_image
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: qevent_intership/stream_data_processor/image

build_docker_image:
  stage: build_image
  only:
    changes:
      - Dockerfile
      - .gitlab-ci.yml
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u regulyar174 -p L4MebxfwqyGUsv7nxgG6 $CI_REGISTRY
    - docker -D build -t $DOCKER_IMAGE_NAME . -e ARROW_DEB_PCKG_SHA256=${ARROW_DEB_PCKG_SHA256} -e CPPZMQ_SHA256=${CPPZMQ_SHA256}

stream_data_processor_build:
  stage: build
  image: $DOCKER_IMAGE_NAME
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make test_main
  artifacts:
    paths:
      - build

stream_data_processor_test:
  stage: test
  script:
    - ./test/test_main
  dependencies:
    - stream_data_processor_build

