consts:
  - gb: 1024 * 1024 * 1024
  - no_space_forecast_unit: 1m

  - win_period: 10m

  - level_df_complex_free_abs_info: 3 * gb
  - level_df_complex_free_abs_warn: 2 * gb
  - level_df_complex_free_abs_crit: 1 * gb

  - level_df_complex_free_percent_info: 5.0
  - level_df_complex_free_percent_warn: 3.0
  - level_df_complex_free_percent_crit: 0.5

  - level_df_inodes_free_abs_info: 1024
  - level_df_inodes_free_abs_warn: 512
  - level_df_inodes_free_abs_crit: 100

  - level_df_inodes_free_percent_info: 10.0
  - level_df_inodes_free_percent_warn: 5.0
  - level_df_inodes_free_percent_crit: 1.0

  - level_forecast_time_till_no_space_left_info: 1h
  - level_forecast_time_till_no_space_left_warn: 30m
  - level_forecast_time_till_no_space_left_crit: 10m

pipeline:
  - graphite:
      global: true
      config: '[[graphite]]'
  - from:
      measurement: df
      group_by: [ 'host', 'kind', 'fs', 'metric' ]
  - barrier:
      idle: 7d
  - flatten:
      name: df_input
      tolerance: 5s
  - filter: NOT isPresent(free)
  - log: "missing field 'free' in {__data__}"

  - filter:
      from: df_input
      condition: NOT isPresent(used)
  - log: "missing field 'used' in {__data__}"

  - filter:
      from: df_input
      condition: NOT isPresent(reserved)
  - log: "missing field 'reserved' in {__data__}"

  - filter:
      from: df_input
      condition: isPresent(free)
  - free.change_rate = derivative(free)
  - window:
      period: win_period
  - eval:
      name: df_rate
      expressions:
        - free.change_rate = mean(free.change_rate)
        - time = time + win_period
        - has_rate = if(isPresent(has_rate), has_rate, TRUE)

  - filter:
      from: df_rate
      condition: NOT isPresent(free) OR NOT isPresent(used) OR NOT isPresent(reserved)
  - log: "missing one of fields: 'free', 'used', 'reserved' in {__data__}"

  - eval:
      from: df_rate
      expressions:
        - no_rate_synced = stateDuration(NOT isPresent(free.change_rate))
  - filter: duration(no_rate_synced, 1s) > win_period + 60s
  - log: "missing union rate in {__data__}"

  - filter:
      from: df_rate
      condition: isPresent(free) AND isPresent(used) AND isPresent(reserved)
  - eval:
      expressions:
        - free.change_rate = if(isPresent(free.change_rate), free.change_rate, 0.0)
        - has_rate = if(isPresent(has_rate), has_rate, FALSE)
  - eval:
      expressions:
        - free = int(free)
        - used = int(used)
        - reserved = int(reserved)
        - capacity = int(free + reserved + used)
        - free.percent = free / (free + reserved + used) * 100.0
        - used.percent = used / (free + reserved + used) * 100.0
        - forecast_time_till_no_space_left = duration(-free / free.change_rate, no_space_forecast_unit)
        - no_space_forecast_unit = no_space_forecast_unit
        - win_period = win_period
  - groupBy: [ 'host', 'kind', 'fs' ]
  - flatten:
      name: df_calc
      tolerance: 2s
      on: metric

  - filter: NOT isPresent(df_complex.free) OR NOT isPresent(df_complex.has_rate)
  - log: "missing inner data in {__data__}"

  - filter:
      from: df_calc
      condition: isPresent(df_complex.free) AND isPresent(df_complex.has_rate)
  - eval:
      name: df_annotate
      expressions:
        - df_complex.used.print = humanBytes(df_complex.used)
        - df_complex.reserved.print = humanBytes(df_complex.reserved)
        - df_complex.free.print = humanBytes(df_complex.free)
        - df_complex.capacity.print = humanBytes(df_complex.free)

  - filter: NOT isPresent(df_inodes.free.percent)
  - log: "missing inner data inodes in {__data__}"

  - filter:
      name: df_inodes
      from: df_annotate
      condition: isPresent(df_inodes.free.percent)
  - eval:
      expressions:
        - level_df_inodes_free_abs_info = level_df_inodes_free_abs_info
        - level_df_inodes_free_abs_warn = level_df_inodes_free_abs_warn
        - level_df_inodes_free_abs_crit = level_df_inodes_free_abs_crit
        - alert-author = '@kv:qrator.net'
        - incident-owners = 'nobody'
        - incident-is-expected = FALSE
        - incident-comment = ''
        - alert-on = 'df-inodes-abs-low'
  - alert:
      id: '{{ .Name }}/{{ .TaskName }}/df-inodes-abs-low:{{ .Group }}'
      details: '<pre>{{ json . }}</pre></p>'
      info: df_inodes.capacity > level_df_inodes_free_abs_info * 2 AND
          df_inodes.free < level_df_inodes_free_abs_info
      warn: kind != 'skip' AND
          df_inodes.capacity > level_df_inodes_free_abs_info * 2 AND
          df_inodes.free" < level_df_inodes_free_abs_warn
      crit: kind == 'show' AND
          df_inodes.capacity > level_df_inodes_free_abs_info * 2 AND
          df_inodes.free < level_df_inodes_free_abs_crit

  - eval:
      from: df_inodes
      expressions:
        - level_df_inodes_free_percent_info = level_df_inodes_free_percent_info
        - level_df_inodes_free_percent_warn = level_df_inodes_free_percent_warn
        - level_df_inodes_free_percent_crit = level_df_inodes_free_percent_crit
        - alert-author = '@kv:qrator.net'
        - incident-owners = 'nobody'
        - incident-is-expected = FALSE
        - incident-comment = ''
        - alert-on = 'df-inodes-percent-low'
  - alert:
      id: '{{ .Name }}/{{ .TaskName }}/df-inodes-percent-low:{{ .Group }}'
      details: '<pre>{{ json . }}</pre></p>'
      info: df_inodes.free.percent < level_df_inodes_free_percent_info
      warn: kind != 'skip' AND
          df_inodes.free.percent < level_df_inodes_free_percent_warn
      crit: kind == 'show' AND
          df_inodes.free.percent" < "level_df_inodes_free_percent_crit

  - filter:
      from: df_inodes
      condition: NOT isPresent(df_inodes.has_rate)
  - log: "lost has rate inodes in {__data__}"

  - filter:
      from: df_inodes
      condition: isPresent(df_inodes.has_rate)
  - eval:
      expressions:
        - level_forecast_time_till_no_space_left_info = level_forecast_time_till_no_space_left_info
        - level_forecast_time_till_no_space_left_warn = level_forecast_time_till_no_space_left_warn
        - level_forecast_time_till_no_space_left_crit = level_forecast_time_till_no_space_left_crit
        - alert-author = '@kv:qrator.net'
        - incident-owners = 'nobody'
        - incident-is-expected = FALSE
        - incident-comment = ''
        - alert-on = 'no-space-left-inodes-forecast'
  - alert:
      id: '{{ .Name }}/{{ .TaskName }}/no-space-left-inodes-forecast:{{ .Group }}'
      details: '<pre>{{ json . }}</pre></p>'
      info: df_inodes.free.change_rate < 0.0 AND
          df_inodes.forecast_time_till_no_space_left < level_forecast_time_till_no_space_left_info
      warn: kind != 'skip' AND df_inodes.free.change_rate < 0.0 AND
          df_inodes.forecast_time_till_no_space_left < level_forecast_time_till_no_space_left_warn
      crit: kind == 'show' AND df_inodes.free.change_rate < 0.0 AND
          df_inodes.forecast_time_till_no_space_left < level_forecast_time_till_no_space_left_crit

  - eval:
      from: df_annotate
      expressions:
        - level_df_complex_free_abs_info = level_df_complex_free_abs_info
        - level_df_complex_free_abs_warn = level_df_complex_free_abs_warn
        - level_df_complex_free_abs_crit = level_df_complex_free_abs_crit
        - alert-author = '@kv:qrator.net'
        - incident-owners = 'nobody'
        - incident-is-expected = FALSE
        - incident-comment = ''
        - alert-on = 'df-space-abs-low:'
  - alert:
      id: '{{ .Name }}/{{ .TaskName }}/df-space-abs-low:{{ .Group }}'
      details: '<pre>{{ json . }}</pre></p>'
      info: df_complex.capacity > level_df_complex_free_abs_info * 2 AND
        df_complex.free < level_df_complex_free_abs_info
      warn: kind != 'skip' AND
        df_complex.capacity > level_df_complex_free_abs_info * 2 AND
        df_complex.free < level_df_complex_free_abs_warn
      crit: kind == 'show' AND
        df_complex.capacity > level_df_complex_free_abs_info * 2 AND
        df_complex.free < level_df_complex_free_abs_crit

  - eval:
      from: df_annotate
      expressions:
        - level_df_complex_free_percent_info = level_df_complex_free_percent_info
        - level_df_complex_free_percent_warn = level_df_complex_free_percent_warn
        - level_df_complex_free_percent_crit = level_df_complex_free_percent_crit
        - alert-author = '@kv:qrator.net'
        - incident-owners = 'nobody'
        - incident-is-expected = FALSE
        - incident-comment = ''
        - alert-on = 'df-space-percent-low'
  - alert:
      id: '{{ .Name }}/{{ .TaskName }}/df-space-percent-low:{{ .Group }}'
      details: '<pre>{{ json . }}</pre></p>'
      info: df_complex.free.percent < level_df_complex_free_percent_info AND
        if(df_complex.has_rate, df_complex.free.change_rate < 0, TRUE)
      warn: kind != 'skip' AND
        df_complex.free.percent < level_df_complex_free_percent_warn AND
        if(df_complex.has_rate, df_complex.free.change_rate < 0, TRUE)
      crit: kind == 'show' AND
        df_complex.free.percent < level_df_complex_free_percent_crit

  - filter:
      from: df_annotate
      condition: NOT isPresent(df_complex.has_rate)
  - log: "lost has rate in {__data__}"

  - filter:
      from: df_annotate
      condition: isPresent(df_complex.has_rate)
  - eval:
      from: df_annotate
      expressions:
        - level_forecast_time_till_no_space_left_info = level_forecast_time_till_no_space_left_info
        - level_forecast_time_till_no_space_left_warn = level_forecast_time_till_no_space_left_warn
        - level_forecast_time_till_no_space_left_crit = level_forecast_time_till_no_space_left_crit
        - alert-author = '@kv:qrator.net'
        - incident-owners = 'nobody'
        - incident-is-expected = FALSE
        - incident-comment = ''
        - alert-on = 'no-space-left-forecast'
  - alert:
      id: '{{ .Name }}/{{ .TaskName }}/no-space-left-forecast:{{ .Group }}'
      details: '<pre>{{ json . }}</pre></p>'
      info: df_complex.free.change_rate < 0.0 AND
        df_complex.forecast_time_till_no_space_left < level_forecast_time_till_no_space_left_info
      warn: kind != 'skip' AND df_complex.free.change_rate < 0.0 AND
        df_complex.forecast_time_till_no_space_left < level_forecast_time_till_no_space_left_warn
      crit: kind == 'show' AND df_complex.free.change_rate < 0.0 AND
        df_complex.forecast_time_till_no_space_left < level_forecast_time_till_no_space_left_crit
